/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.PizzabaseControlador;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import sun.awt.image.ByteArrayImageSource;
import sun.awt.image.ToolkitImage;

/**
 *
 * @author bryanstm
 */
public class Vista_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Administrador
     */
    PizzabaseControlador pc = new PizzabaseControlador(this);
    byte[] imagen;
    
    public Vista_Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_pizza = new javax.swing.JPanel();
        jl_nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jl_presentacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jc_presentacion = new javax.swing.JComboBox();
        jt_precio = new javax.swing.JTextField();
        jb_cargarpizza = new javax.swing.JButton();
        jl_imgpizza = new javax.swing.JLabel();
        jb_actualizar = new javax.swing.JButton();
        jb_ingresar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jc_tamano = new javax.swing.JComboBox();
        jt_buscar = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        panel_ingrediente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jb_cargaringre = new javax.swing.JButton();
        jl_imgingre = new javax.swing.JLabel();
        jt_ingreid = new javax.swing.JTextField();
        jt_nombreingre = new javax.swing.JTextField();
        jt_precion = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jc_tipoingre = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jP_carne = new javax.swing.JPanel();
        jl_precarne = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jt_precarne = new javax.swing.JTextField();
        jt_gracarne = new javax.swing.JTextField();
        jt_anicarne = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jt_buscarne = new javax.swing.JTextField();
        jb_buscarne = new javax.swing.JButton();
        jb_actucarne = new javax.swing.JButton();
        jb_ingrecarne = new javax.swing.JButton();
        jb_elicarne = new javax.swing.JButton();
        jP_salsa = new javax.swing.JPanel();
        jl_azusalsa = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jt_azusalsa = new javax.swing.JTextField();
        jt_grasalsa = new javax.swing.JTextField();
        jt_carbosalsa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jt_bussalsa = new javax.swing.JTextField();
        jb_bussalsa = new javax.swing.JButton();
        jb_actusalsa = new javax.swing.JButton();
        jb_ingresalsa = new javax.swing.JButton();
        jb_elisalsa = new javax.swing.JButton();
        jP_vegetal = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jt_carbovegetales = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jt_busvegetales = new javax.swing.JTextField();
        jb_busvegetales = new javax.swing.JButton();
        jb_actuvegetales = new javax.swing.JButton();
        jb_ingrevegetales = new javax.swing.JButton();
        jb_elivegetales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_nombre.setText("Nombre:");

        jLabel1.setText("Tamaño:");

        jl_presentacion.setText("Presentación:");

        jLabel2.setText("Precio:");

        jLabel3.setText("Foto:");

        jc_presentacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "8", "12" }));
        jc_presentacion.setToolTipText("");

        jb_cargarpizza.setText("Cargar");
        jb_cargarpizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cargarpizzaActionPerformed(evt);
            }
        });

        jl_imgpizza.setText("jLabel4");
        jl_imgpizza.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jb_actualizar.setText("Actualizar");

        jb_ingresar.setText("Ingresar");
        jb_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresarActionPerformed(evt);
            }
        });

        jb_eliminar.setText("Eliminar");

        jLabel5.setText("Buscar ID:");

        jc_tamano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pequeña", "Mediana", "Grande" }));

        jb_buscar.setText("Buscar");

        javax.swing.GroupLayout panel_pizzaLayout = new javax.swing.GroupLayout(panel_pizza);
        panel_pizza.setLayout(panel_pizzaLayout);
        panel_pizzaLayout.setHorizontalGroup(
            panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pizzaLayout.createSequentialGroup()
                .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pizzaLayout.createSequentialGroup()
                        .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_pizzaLayout.createSequentialGroup()
                                .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_pizzaLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pizzaLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1)))
                                .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_pizzaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_pizzaLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jc_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel_pizzaLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jb_actualizar))
                            .addGroup(panel_pizzaLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jl_nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_pizzaLayout.createSequentialGroup()
                                .addComponent(jb_ingresar)
                                .addGap(74, 74, 74)
                                .addComponent(jb_eliminar))
                            .addGroup(panel_pizzaLayout.createSequentialGroup()
                                .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_presentacion)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_pizzaLayout.createSequentialGroup()
                                        .addComponent(jb_cargarpizza)
                                        .addGap(44, 44, 44)
                                        .addComponent(jl_imgpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jc_presentacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jt_precio))))
                            .addComponent(jb_buscar))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(panel_pizzaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        panel_pizzaLayout.setVerticalGroup(
            panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pizzaLayout.createSequentialGroup()
                .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pizzaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_presentacion)
                            .addComponent(jc_presentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pizzaLayout.createSequentialGroup()
                        .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_nombre)
                            .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)))
                .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jb_cargarpizza)
                    .addComponent(jl_imgpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panel_pizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_actualizar)
                    .addComponent(jb_ingresar)
                    .addComponent(jb_eliminar))
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("Pizza", panel_pizza);

        jLabel4.setText("Ingrediente ID:");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Precio Porcion:");

        jLabel8.setText("Cantidad:");

        jLabel9.setText("Tipo:");

        jLabel10.setText("Foto");

        jb_cargaringre.setText("Cargar");
        jb_cargaringre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cargaringreActionPerformed(evt);
            }
        });

        jl_imgingre.setText("imagen Ingrediente");
        jl_imgingre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jc_tipoingre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carne", "Vegetal", "Salsa" }));
        jc_tipoingre.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jc_tipoingreComponentAdded(evt);
            }
        });
        jc_tipoingre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_tipoingreActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jc_tipoingre, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), jP_carne, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jl_precarne.setText("Presentación:");

        jLabel11.setText("Cantidad Grasa:");

        jLabel12.setText("Animal");

        jt_precarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_precarneActionPerformed(evt);
            }
        });

        jLabel13.setText("Buscar Carne:");

        jb_buscarne.setText("Buscar");

        jb_actucarne.setText("Actualizar");
        jb_actucarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actucarneActionPerformed(evt);
            }
        });

        jb_ingrecarne.setText("Ingresar");
        jb_ingrecarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingrecarneActionPerformed(evt);
            }
        });

        jb_elicarne.setText("Eliminar");

        javax.swing.GroupLayout jP_carneLayout = new javax.swing.GroupLayout(jP_carne);
        jP_carne.setLayout(jP_carneLayout);
        jP_carneLayout.setHorizontalGroup(
            jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_carneLayout.createSequentialGroup()
                .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_carneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_precarne)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(24, 24, 24)
                        .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_buscarne)
                            .addGroup(jP_carneLayout.createSequentialGroup()
                                .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_gracarne, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jP_carneLayout.createSequentialGroup()
                                        .addComponent(jt_precarne, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                        .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_carneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_anicarne, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_carneLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_elicarne)
                                    .addComponent(jb_buscarne)))))
                    .addGroup(jP_carneLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jb_actucarne)
                        .addGap(37, 37, 37)
                        .addComponent(jb_ingrecarne)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jP_carneLayout.setVerticalGroup(
            jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_carneLayout.createSequentialGroup()
                .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_carneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_precarne)
                            .addComponent(jt_precarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP_carneLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jt_anicarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_gracarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jt_buscarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_buscarne)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_carneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_actucarne)
                    .addComponent(jb_ingrecarne)
                    .addComponent(jb_elicarne))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jl_azusalsa.setText("Azucares");

        jLabel14.setText("Cantidad Grasa:");

        jLabel15.setText("Carbohidratos:");

        jt_azusalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_azusalsaActionPerformed(evt);
            }
        });

        jLabel16.setText("Buscar Carne:");

        jb_bussalsa.setText("Buscar");

        jb_actusalsa.setText("Actualizar");
        jb_actusalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actusalsaActionPerformed(evt);
            }
        });

        jb_ingresalsa.setText("Ingresar");
        jb_ingresalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresalsaActionPerformed(evt);
            }
        });

        jb_elisalsa.setText("Eliminar");

        javax.swing.GroupLayout jP_salsaLayout = new javax.swing.GroupLayout(jP_salsa);
        jP_salsa.setLayout(jP_salsaLayout);
        jP_salsaLayout.setHorizontalGroup(
            jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_salsaLayout.createSequentialGroup()
                .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_salsaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_azusalsa)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jP_salsaLayout.createSequentialGroup()
                                .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_azusalsa, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jt_grasalsa))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addComponent(jt_bussalsa))
                        .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_salsaLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jb_bussalsa))
                            .addGroup(jP_salsaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_carbosalsa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jP_salsaLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jb_actusalsa)
                        .addGap(37, 37, 37)
                        .addComponent(jb_ingresalsa)
                        .addGap(51, 51, 51)
                        .addComponent(jb_elisalsa)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jP_salsaLayout.setVerticalGroup(
            jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_salsaLayout.createSequentialGroup()
                .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_salsaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_azusalsa)
                            .addComponent(jt_azusalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP_salsaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jt_carbosalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jt_grasalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jt_bussalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_bussalsa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_salsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_actusalsa)
                    .addComponent(jb_ingresalsa)
                    .addComponent(jb_elisalsa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setText("Carbohidratos:");

        jLabel22.setText("Buscar Vegetales:");

        jb_busvegetales.setText("Buscar");

        jb_actuvegetales.setText("Actualizar");
        jb_actuvegetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actuvegetalesActionPerformed(evt);
            }
        });

        jb_ingrevegetales.setText("Ingresar");
        jb_ingrevegetales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingrevegetalesActionPerformed(evt);
            }
        });

        jb_elivegetales.setText("Eliminar");

        javax.swing.GroupLayout jP_vegetalLayout = new javax.swing.GroupLayout(jP_vegetal);
        jP_vegetal.setLayout(jP_vegetalLayout);
        jP_vegetalLayout.setHorizontalGroup(
            jP_vegetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_vegetalLayout.createSequentialGroup()
                .addGroup(jP_vegetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_vegetalLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jb_actuvegetales)
                        .addGap(37, 37, 37)
                        .addComponent(jb_ingrevegetales)
                        .addGap(51, 51, 51)
                        .addComponent(jb_elivegetales))
                    .addGroup(jP_vegetalLayout.createSequentialGroup()
                        .addGroup(jP_vegetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_vegetalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21)
                                .addGap(33, 33, 33)
                                .addComponent(jt_carbovegetales, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(jP_vegetalLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(jt_busvegetales, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addComponent(jb_busvegetales)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jP_vegetalLayout.setVerticalGroup(
            jP_vegetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_vegetalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jP_vegetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jt_carbovegetales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jP_vegetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jt_busvegetales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_busvegetales))
                .addGap(40, 40, 40)
                .addGroup(jP_vegetalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_actuvegetales)
                    .addComponent(jb_ingrevegetales)
                    .addComponent(jb_elivegetales))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_vegetal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jP_salsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jP_carne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_vegetal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jP_salsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jP_carne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jP_salsa.setVisible(false);
        jP_vegetal.setVisible(false);

        javax.swing.GroupLayout panel_ingredienteLayout = new javax.swing.GroupLayout(panel_ingrediente);
        panel_ingrediente.setLayout(panel_ingredienteLayout);
        panel_ingredienteLayout.setHorizontalGroup(
            panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ingredienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ingredienteLayout.createSequentialGroup()
                        .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_ingreid)
                            .addComponent(jt_nombreingre)
                            .addComponent(jt_precion, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ingredienteLayout.createSequentialGroup()
                                .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jc_tipoingre, 0, 100, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_ingredienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jb_cargaringre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_imgingre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ingredienteLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panel_ingredienteLayout.setVerticalGroup(
            panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ingredienteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jt_ingreid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9)
                        .addComponent(jt_nombreingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jc_tipoingre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ingredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jb_cargaringre)
                    .addComponent(jt_precion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_imgingre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingrediente", panel_ingrediente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cargarpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cargarpizzaActionPerformed
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File foto = fc.getSelectedFile();
            System.out.println("Un archivo fue seleccionado...");
            
            InputStream is = null;
            try {
                is = new FileInputStream(foto); //lo abrimos. Lo importante es que sea un InputStream
            } catch (FileNotFoundException ex) {
                System.out.println("ERROR CON EL ARCHIVO!");
            }
            byte[] buffer = new byte[(int) foto.length()]; //creamos el buffer
            try {
                int readers = is.read(buffer); //leemos el archivo al buffer
            } catch (IOException ex) {
                System.out.println("ERROR BUFFER ARCHIVO!");
            }
            imagen = buffer; //lo guardamos en la variable foto
            
            //>>>>>>>>>>>
            
            Image cargaImg=new ToolkitImage(new ByteArrayImageSource(buffer)); //lo convertimos a Image
            jl_imgpizza.setIcon(new ImageIcon(cargaImg)); //cargamos en el JLabel la imagen como icono
            
            //<<<<<<<<<<<
            
        } else {
            System.out.println("Cancelar seleccion...");
        }
    }//GEN-LAST:event_jb_cargarpizzaActionPerformed

    private void jc_tipoingreComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jc_tipoingreComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_tipoingreComponentAdded

    private void jb_cargaringreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cargaringreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cargaringreActionPerformed

    private void jc_tipoingreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_tipoingreActionPerformed
        if((String)jc_tipoingre.getSelectedItem() == "Carne"){
            jP_salsa.setVisible(false);
            jP_vegetal.setVisible(false);
            jP_carne.setVisible(true);
            
        }
        
        if((String)jc_tipoingre.getSelectedItem() == "Vegetal"){
            jP_carne.setVisible(false);
            jP_salsa.setVisible(false);
            jP_vegetal.setVisible(true);
            
        }
        
        if((String)jc_tipoingre.getSelectedItem() == "Salsa"){
            jP_vegetal.setVisible(false);
            jP_carne.setVisible(false);
            jP_salsa.setVisible(true);
            
        }
    }//GEN-LAST:event_jc_tipoingreActionPerformed

    private void jt_precarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_precarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_precarneActionPerformed

    private void jb_actucarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actucarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_actucarneActionPerformed

    private void jb_ingrecarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingrecarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ingrecarneActionPerformed

    private void jt_azusalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_azusalsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_azusalsaActionPerformed

    private void jb_actusalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actusalsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_actusalsaActionPerformed

    private void jb_ingresalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresalsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ingresalsaActionPerformed

    private void jb_ingrevegetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingrevegetalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ingrevegetalesActionPerformed

    private void jb_actuvegetalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actuvegetalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_actuvegetalesActionPerformed

    private void jb_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresarActionPerformed
        boolean result = pc.IngresarPizzabase(imagen, 1, jt_nombre.getText(), (String)jc_tamano.getSelectedItem(),
                (String)jc_presentacion.getSelectedItem(), Double.parseDouble(jt_precio.getText()));
         //Double.parseDouble(jt_precio.getText())
        
        if (result){
            System.out.println("true ingresar pizza action");
        }else{
            System.out.println("false ingresar pizza action");
        }
    }//GEN-LAST:event_jb_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP_carne;
    private javax.swing.JPanel jP_salsa;
    private javax.swing.JPanel jP_vegetal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_actucarne;
    private javax.swing.JButton jb_actusalsa;
    private javax.swing.JButton jb_actuvegetales;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_buscarne;
    private javax.swing.JButton jb_bussalsa;
    private javax.swing.JButton jb_busvegetales;
    private javax.swing.JButton jb_cargaringre;
    private javax.swing.JButton jb_cargarpizza;
    private javax.swing.JButton jb_elicarne;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_elisalsa;
    private javax.swing.JButton jb_elivegetales;
    private javax.swing.JButton jb_ingrecarne;
    private javax.swing.JButton jb_ingresalsa;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JButton jb_ingrevegetales;
    private javax.swing.JComboBox jc_presentacion;
    private javax.swing.JComboBox jc_tamano;
    private javax.swing.JComboBox jc_tipoingre;
    private javax.swing.JLabel jl_azusalsa;
    private javax.swing.JLabel jl_imgingre;
    private javax.swing.JLabel jl_imgpizza;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_precarne;
    private javax.swing.JLabel jl_presentacion;
    private javax.swing.JTextField jt_anicarne;
    private javax.swing.JTextField jt_azusalsa;
    private javax.swing.JTextField jt_buscar;
    private javax.swing.JTextField jt_buscarne;
    private javax.swing.JTextField jt_bussalsa;
    private javax.swing.JTextField jt_busvegetales;
    private javax.swing.JTextField jt_carbosalsa;
    private javax.swing.JTextField jt_carbovegetales;
    private javax.swing.JTextField jt_gracarne;
    private javax.swing.JTextField jt_grasalsa;
    private javax.swing.JTextField jt_ingreid;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_nombreingre;
    private javax.swing.JTextField jt_precarne;
    private javax.swing.JTextField jt_precio;
    private javax.swing.JTextField jt_precion;
    private javax.swing.JPanel panel_ingrediente;
    private javax.swing.JPanel panel_pizza;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
